config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'videos', to: 'static_pages#videos', as: :video_portfolio
  get 'photos', to: 'static_pages#photos', as: :photo_portfolio
  get 'skiing', to: 'static_pages#skiing', as: :skiing_portfolio
  get 'about', to: 'static_pages#about', as: :about
  
  scope '/admin' do
    resources :videos do
      post :update_row_order, on: :collection
    end
    resources :photos do
      post :update_photos_order, on: :collection
      post :update_skiing_order, on: :collection
      post :update_about_order, on: :collection
    end
  end
  
  devise_for :users, skip: [:registrations, :sessions]
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  include RankedModel

  CATEGORIES = ["Photos", "Skiing", "About"]

  scope :photos, -> { where(category: "Photos") }
  scope :skiing, -> { where(category: "Skiing") }
  scope :about, -> { where(category: "About") }

  ranks :photos_order, scope: :photos
  ranks :skiing_order, scope: :skiing
  ranks :about_order, scope: :about

  has_attached_file :image, styles: {
    small: '300>',
    medium: '650>',
    large: '1000>'
  }

  validates_attachment :image, presence: true, content_type: { content_type: /\Aimage\/.*\Z/ }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
  include RankedModel
  ranks :row_order
  validates :vimeo_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.photos.rank(:photos_order)
    @skiing = Photo.skiing.rank(:skiing_order)
    @about = Photo.about.rank(:about_order)
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_photos_order
    @photo = Photo.find(photo_params[:photo_id])
    @photo.photos_order_position = photo_params[:photos_order_position]
    @photo.save

    render nothing: true
  end

  def update_skiing_order
    @photo = Photo.find(photo_params[:photo_id])
    @photo.skiing_order_position = photo_params[:skiing_order_position]
    @photo.save

    render nothing: true
  end

  def update_about_order
    @photo = Photo.find(photo_params[:photo_id])
    @photo.about_order_position = photo_params[:about_order_position]
    @photo.save

    render nothing: true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image, :category, :caption, :photo_id, :photos_order_position, :skiing_order_position, :about_order_position)
    end
end

app/controllers/static_pages_controller.rb
# require 'httparty'

class StaticPagesController < ApplicationController
  def home
    @home = true
    @photos = Photo.photos.rank(:photos_order)
    @skiing = Photo.skiing.rank(:skiing_order)
    @videos = Video.rank(:row_order).all
  end

  def videos
    @home = true
    @videos = Video.rank(:row_order).all
  end

  def photos
    @home = true
    @photos = Photo.photos.rank(:photos_order)
  end

  def skiing
    @home = true
    @skiing = Photo.skiing.rank(:skiing_order)
  end

  def about
    @home = true
    @about = Photo.about.rank(:about_order)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.rank(:row_order).all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    response = HTTParty.get("https://vimeo.com/api/oembed.json?url=#{CGI.escape(@video.vimeo_url)}")
    video_object = JSON.parse(response.body)
    @video.thumbnail_url = video_object["thumbnail_url"]

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    response = HTTParty.get("https://vimeo.com/api/oembed.json?url=#{CGI.escape(video_params['vimeo_url'])}")
    video_object = JSON.parse(response.body)
    @video.thumbnail_url = video_object["thumbnail_url"]

    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_row_order
    @video = Video.find(video_params[:video_id])
    @video.row_order_position = video_params[:row_order_position]
    @video.save

    render nothing: true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:vimeo_url, :video_id, :row_order_position)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_flashes.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert <%= alert_for(message_type) %> alert-dismissible">
    <button aria-label="Close" class="close" data-dismiss="alert" type="button">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="row">
  <h1 id="home-header" class="text-center">
    <%= link_to root_path, class: 'header-link' do %>
      <%= image_tag "etienne_logo_black.jpg", id: "header-logo" %>
      Etienne Arent
      <%= image_tag "etienne_logo_black.jpg", id: "header-logo" %>
    <% end %>
  </h1>
</header>

app/views/layouts/_icons.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/icons/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/icons/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/icons/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/icons/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/icons/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/icons/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/icons/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/icons/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/icons/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/icons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/icons/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/icons/favicon-16x16.png">
<link rel="manifest" href="/icons/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_navigation.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Videos", videos_path %></li>
          <li><%= link_to "Photos", photos_path %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">

    <title>Etienne Arent</title>
    <%= render "layouts/icons" %>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" type="text/css" media="screen" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/helpers/jquery.fancybox-media.js"></script>
    <%= csrf_meta_tags %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class=<%= "home" if @home %>>
    <div class="container-fluid">
      <%= render "layouts/navigation" %>
      <%= render "layouts/flashes" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/photos/_form.html.erb
<% if @photo.image.exists? %>
  <%= image_tag @photo.image.url(:small), id: 'image-preview', class: 'img-responsive' %>
<% else %>
  <%= image_tag 'placeholder.png', id: 'image-preview', class: 'img-responsive' %>
<% end %>

<%= simple_form_for(@photo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :image, as: :file, input_html: { onChange: 'loadFile(event)' } %>
    <%= f.input :caption %>
    <%= f.input :category, collection: Photo::CATEGORIES, include_blank: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Photos</h1>

<div>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#photos" aria-controls="photos" role="tab" data-toggle="tab">Photos</a></li>
    <li role="presentation"><a href="#skiing" aria-controls="skiing" role="tab" data-toggle="tab">Skiing</a></li>
    <li role="presentation"><a href="#about" aria-controls="about" role="tab" data-toggle="tab">About</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="photos">
      <table class="table table-striped" id="sortable_photos">
        <thead>
          <tr>
            <th>Photos</th>
            <th>Caption</th>
            <th>Category</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @photos.each do |photo| %>
            <tr data-photo-id="<%= photo.id %>" class="item">
              <td><%= image_tag photo.image.url(:small), class: "img-responsive" %></td>
              <td><%= photo.caption %></td>
              <td><%= photo.category %></td>
              <td><%= link_to 'Show', photo %></td>
              <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
              <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Photo', new_photo_path %>
    </div>

    <div role="tabpanel" class="tab-pane fade" id="skiing">
      <table class="table table-striped" id="sortable_skiing">
        <thead>
          <tr>
            <th>Skiing</th>
            <th>Caption</th>
            <th>Category</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @skiing.each do |photo| %>
            <tr data-photo-id="<%= photo.id %>" class="item">
              <td><%= image_tag photo.image.url(:small), class: "img-responsive" %></td>
              <td><%= photo.caption %></td>
              <td><%= photo.category %></td>
              <td><%= link_to 'Show', photo %></td>
              <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
              <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Photo', new_photo_path %>
    </div>

    <div role="tabpanel" class="tab-pane fade" id="about">
      <table class="table table-striped" id="sortable_about">
        <thead>
          <tr>
            <th>About</th>
            <th>Caption</th>
            <th>Category</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @about.each do |photo| %>
            <tr data-photo-id="<%= photo.id %>" class="item">
              <td><%= image_tag photo.image.url(:small), class: "img-responsive" %></td>
              <td><%= photo.caption %></td>
              <td><%= photo.category %></td>
              <td><%= link_to 'Show', photo %></td>
              <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
              <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Photo', new_photo_path %>
    </div>
  </div><!-- /.tab-content -->
</div>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @photo.image.url(:large) %>
</p>

<p>
  <%= @photo.caption %>
</p>

<p>
  <strong>Category:</strong> <%= @photo.category %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/static_pages/about.html.erb
<%= render "layouts/header" %>

<div class="row">
  <div class="col-md-6 col-md-offset-3" id="about">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <%= image_tag @about.first.image.url(:large), class: 'img-responsive' %>
        </div>
        <% @about.drop(1).each do |photo| %>
          <div class="item">
            <%= image_tag photo.image.url(:large), class: 'img-responsive' %>
          </div>
        <% end %>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

    <div id="trusted-by">
      <h4 class="about-link">Trusted By</h4>
      <div class="row">
        <div class="col-sm-12">
          <%= image_tag "logos_aligned.png", class: "img-responsive" %>
        </div>
      </div>
    </div>
    
    <p class="quote text-center">
      “Yeah here I come just passing through, follow me beyond the mountain, 
      howl at the ol' big moon. Yeah strip them clothes right off your body, 
      dress your skin in sticks and stones. Doesn't matter where were headed 
      cause some us were built to roam.”
      <br>
      —Alejandrio Rose-Garcia
    </p>
  </div>
</div>

<footer class="row text-center">
  <%= link_to "Email", "mailto:etjarent@gmail.com", target: "_blank", class: 'about-link' %>
  /
  <%= link_to "Vimeo", "https://vimeo.com/user966917", target: "_blank", class: 'about-link' %>
  /
  <%= link_to "Instagram", "https://www.instagram.com/etiennearent/", target: "_blank", class: 'about-link' %>
</footer>

app/views/static_pages/home.html.erb
<%= render "layouts/header" %>

<div class="row text-center">
  <div class="col-xs-4 heading">
    <h3><%= link_to 'Videos', video_portfolio_path, class: 'column-header-link' %></h3>
  </div>
  <div class="col-xs-4 heading">
    <h3><%= link_to 'Photography', photo_portfolio_path, class: 'column-header-link' %></h3>
  </div>
  <div class="col-xs-4 heading">
    <h3><%= link_to 'Skiing', skiing_portfolio_path, class: 'column-header-link' %></h3>
  </div>
</div>

<div class="row">
  <div class="col-xs-4" id="left">
    <% @videos.each do |video| %>
      <%= link_to video["vimeo_url"], class: "fancybox-media" do %>
        <span class="overlay center-block"></span>
        <%= image_tag video["thumbnail_url"], class: "img-responsive" %>
      <% end %>
    <% end %>
  </div>   
  <div class="col-xs-4" id="middle">
    <% @photos.each do |photo| %>
      <%= link_to photo.image.url(:original), title: photo.caption, class: "fancybox", rel: "photos" do %>
        <span class="overlay center-block"></span>
        <%= image_tag photo.image.url(:medium), class: 'img-responsive' %>
      <% end %>
    <% end %>
  </div>
  <div class="col-xs-4" id="right">
    <% @skiing.each do |photo| %>
      <%= link_to photo.image.url(:original), title: photo.caption, class: "fancybox", rel: "skiing" do %>
        <span class="overlay center-block"></span>
        <%= image_tag photo.image.url(:medium), class: 'img-responsive' %>
      <% end %>
    <% end %>
  </div>
</div>

<footer class="row text-center">
  <%= link_to "About", about_path, id: "info-link" %>
</footer>

app/views/static_pages/photos.html.erb
<%= render "layouts/header" %>

<div class="row text-center">
  <div class="col-md-6 col-md-offset-3 heading">
    <h3 class="column-header">Photography</h3>
  </div>
</div>

<div class="row">  
  <div class="col-md-6 col-md-offset-3" id="middle">
    <% @photos.each do |photo| %>
      <%= link_to photo.image.url(:original), title: photo.caption, class: "fancybox", rel: "photos" do %>
        <span class="overlay center-block"></span>
        <%= image_tag photo.image.url(:large), class: 'img-responsive' %>
      <% end %>
    <% end %>
  </div>
</div>

<footer class="row text-center">
  <%= link_to "About", about_path, id: "info-link" %>
</footer>

app/views/static_pages/skiing.html.erb
<%= render "layouts/header" %>

<div class="row text-center">
  <div class="col-md-6 col-md-offset-3 heading">
    <h3 class="column-header">Skiing</h3>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3" id="middle">
    <% @skiing.each do |photo| %>
      <%= link_to photo.image.url(:original), title: photo.caption, class: "fancybox", rel: "photos" do %>
        <span class="overlay center-block"></span>
        <%= image_tag photo.image.url(:large), class: 'img-responsive' %>
      <% end %>
    <% end %>
  </div>
</div>

<footer class="row text-center">
  <%= link_to "About", about_path, id: "info-link" %>
</footer>

app/views/static_pages/videos.html.erb
<%= render "layouts/header" %>

<div class="row text-center">
  <div class="col-md-6 col-md-offset-3 heading">
    <h3 class="column-header">Videos</h3>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3" id="middle">
    <% @videos.each do |video| %>
      <%= link_to video["vimeo_url"], class: "fancybox-media" do %>
        <span class="overlay center-block"></span>
        <%= image_tag video["thumbnail_url"], class: "img-responsive" %>
      <% end %>
    <% end %>
  </div>   
</div>

<footer class="row text-center">
  <%= link_to "About", about_path, id: "info-link" %>
</footer>

app/views/videos/_form.html.erb
<%= simple_form_for(@video) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :vimeo_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Videos</h1>

<table class="table table-striped" id="sortable_videos">
  <thead>
    <tr>
      <th>Thumbnail</th>
      <th>Vimeo url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr data-video-id="<%= video.id %>" class="item">
        <td><%= image_tag video.thumbnail_url, class: "img-responsive" %></td>
        <td><%= video.vimeo_url %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vimeo url:</strong>
  <%= @video.vimeo_url %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>